apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  URL: google.com
---
apiVersion: v1
kind: Pod
metadata:
  name: pod04
spec:
  containers:
  - name: centos
    image: rkalluru/debug:centos8
    envFrom:
      - configMapRef:
          name: game-demo

