apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
---

apiVersion: v1
kind: Pod
metadata:
  name: pod07
spec:
  serviceAccountName: sample
  containers:
  - name: centos
    image: rkalluru/debug:centos8
