apiVersion: v1
kind: Pod
metadata:
  name: pod08
spec:
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  containers:
  - name: centos
    image: rkalluru/debug:centos8
